### ISSUE TITLE
Format Scatterplot (Flight Time v Price) 

### ISSUE THREAD

**Issue by jeslacourse** [STA141B-ProjectTeam/FinalProject#1]
The existing scatter plot is a qplot and would benefit from an upgrade to ggplot or plotly. 

![image](https://user-images.githubusercontent.com/22861743/76639154-dff9f480-650a-11ea-8e23-30aefb4e4c14.png)

- Add a title, format the axis labels
- Format to logarithmic scale (this shortens the tail, minimizes outlier impact, and shows more detail at the lower end) 
- Add a stopover variable class (that's `via`) to visualize how the stop overs add to the duration of the flight
- If using ggplot I'd recommend adding `+ theme_bw()` or a similar theme to give the graphic a clean look. 

Keep note of the questions you're asking yourself when you look at the graphic, how can you answer those? Our users will likely have the same questions! 

- Add summary statistics: 
-- I'd recommend focusing on flight statistics (can you use via as well? Get creative)
-- Quickest flights, quickest flights with no/one stopover, median flight time (tell me why the median and not the mean?) 
-- Price statistics are going to be utilized in histo tab, so let's avoid that redundancy?

**Comment by vabudilov** [comment]
what are expected benefits if switched to ggplot and/or plotly? Not clear at all.

**Comment by jeslacourse** [comment]
Both ggplot and plotly are (a) more versatile and (b) are within the scope of the class  compared to  base modeling. 
Plus, plotly is dynamic, so with appropriate classes the user can visualize comparisons of the impact of number of stopovers on flight times, for example.

**Comment by vabudilov** [comment]
Both points are too general for the project. How can ggplot and plotly
improve this specific project? What is the goal?
I don't mind if you change to ggplot or whatever else, I just do not
understand the :profit: to the project

**Comment by jeslacourse** [comment]
@vabudilov This sounds like a higher level issue. When you picked the API, what was the focus of the project? Why doesn't plotting price and time showing stopovers meet that goal?

**Comment by vabudilov** [comment]
I have no objections if someone decides to switch from qplot to ANY other
thing. It doesn't matter. You may better know if it is important or not for
this possibly not-to-be-born project. :)
The most related note seems to be "plotting price and tim e showing
stopovers " which is absolutely good idea and I vote for doing it.


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by vabudilov** [comment]
@jeslacourse  your comments (some of them) are so exciting.  I was thinking about your Qs
1) When you picked the API, what was the focus of the project? 
2) Why doesn't plotting price and time showing stopovers meet that goal?
I'd answer/comment in reverse order.
2a.  After the API already picked, showing price and time with stopovers look natural and useful.
2b. I never thought that plotting is within the scope of the project. Creating a plot was a kind of provocation, a way of pushing participants toward contributing. You agreed to elaborate your plot as well. So, the idea was not just mine, but yours as well.  The real project wouldn't need a plot.
1. When I picked API, the idea was just "why not" as far as I was interested in learning how commercial flights are sold.  It was just simple.
