### ISSUE TITLE
Implement Round Trip Functionality

### ISSUE THREAD

**Issue by jeslacourse** [STA141B-ProjectTeam/FinalProject#4]
This will be an interesting one, how does it affect the graphics? What visuals would be better or do we really just want summary statistics here?

**Comment by vabudilov** [comment]
it would be good to refactor existing doit():
1) extract AMADEUS data retrieval into a separate function
2) rewrite doit (or create another function) making it working with both one-way and roundtrip JSON
I think there will be no changes to the outputs

**Comment by vabudilov** [comment]
This is the most essential development need at this stage, indeed. 
There are some (if not many) other very important functions to implement if there is any interest in the project.
