### ISSUE TITLE
Are we going to create local storage for saving recent searches?

### ISSUE THREAD

**Issue by vabudilov** [STA141B-ProjectTeam/FinalProject#7]
Can you clarify if we'll be using local storage for search history?

**Comment by jeslacourse** [comment]
It would be a good option and should increase the speed of the project for at least the current call. We could, in theory, store the last two or three calls to create a history as well. I'll look into what it'll take.

**Comment by vabudilov** [comment]
ok
However, I did not understand how could local storage increase the speed of the current call? 
What are we going to store? When our storage has to be updated?
